# Generated by Django 5.0.6 on 2024-06-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_shippingadress_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='adress',
            new_name='address',
        ),
    ]
